name: CI Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.12]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }} 

      - name: Create environment 
        run: make install

      - name: Test Code
        env: # Or as an environment variable
        super_secret: ${{ secrets.SERVER_HOSTNAME }}
        run: python3 test.py
